### ISSUE TITLE
[Suggestion] Make the widgets more fluent instead of apple style

### ISSUE THREAD

**Issue by foursplaysroblox** [creewick/uWidgets#10]
make an option to make the widgets look more fluent instead of apple style

**Comment by foursplaysroblox** [comment]
> Hi! Yes, I plan to make such an option, but I'm not sure yet, what exactly should I change.
> 
> I have this variant in my mind:
> 
> * Change font family to Segoe UI
> * Use native window frame (slightly rounded in win11, not rounded in win10)
> 
> Like on this screenshot, but without window action buttons
> 
> <img alt="Screenshot" width="395" src="https://private-user-images.githubusercontent.com/32510906/357413401-2f15785c-9a6e-4503-bd0d-a60319a04706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjcyMjksIm5iZiI6MTcyMzg2NjkyOSwicGF0aCI6Ii8zMjUxMDkwNi8zNTc0MTM0MDEtMmYxNTc4NWMtOWE2ZS00NTAzLWJkMGQtYTYwMzE5YTA0NzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDAzNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MDZiZmNiNWVjYzRhMzFmODdjZjNiYmE4NDFiM2I0NDkxZmNkMGFkMGZiOGFkY2YyZWZlYmE5N2ZlMTc2NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ztDFyjPExEmAIhiK36rmba84bKBgIhJTv9nT8NkD0E">
> Tell me, what do you think? Anything specific you want to change?

looks good just don't add the minimize, maximize and close button

**Comment by creewick** [comment]
Implemented in v0.5.0
Check the Windows preset in Appearance settings
