### ISSUE TITLE
Clock UI layout suggestion

### ISSUE THREAD

**Issue by wahyuabrory** [creewick/uWidgets#14]
**Is your feature request related to a problem? Please describe.**
When looking at the clock widget, I find it difficult to see the time properly. The only indicators for different time zones are numbers like (-7, -12, etc.), which isn't very clear.

**Describe the solution you'd like**
I would like a redesigned clock widget similar to Apple's, where the clock changes color based on the time of day—white for daylight and a darker color for nighttime. Additionally, the time zone should be displayed at the bottom of each clock.

**Additional context**
- The current widget:
![image](https://github.com/user-attachments/assets/7a36f8ad-9edc-43d5-8487-e5be5427eebe)
- The requested feature: 
![image](https://github.com/user-attachments/assets/e2ab1245-032e-41e2-b34e-16feefe5079e)
- The design for a smaller clock size: 
![WhatsApp Image 2024-08-16 at 09 37 44_837accdb](https://github.com/user-attachments/assets/2645f434-3836-436d-9aa3-9eaf7231a0d8)

**Comment by creewick** [comment]
<img width="368" alt="Screenshot 2024-08-26 at 10 50 09 PM" src="https://github.com/user-attachments/assets/1faafa63-0bd5-4e97-89bf-5dc8809ba5a9" align="right">

Added in 0.5.4

- City name abbreviation for Analog Clock and World Clock (small)
- Full city name, date, time difference for World Clock (wide)
