### ISSUE TITLE
The widgets are not translucent even enabled high power mode.

### ISSUE THREAD

**Issue by sq4567** [creewick/uWidgets#15]
**Desktop**
 - OS: Windows 11 22H2
 - Version: 0.4.2.0

**Crash log**
Attach the `crash_log.txt` file or paste its content here, if the app crashed.

![image](https://github.com/user-attachments/assets/7f5eb3c0-25c6-443c-83f5-ecaec3f17d30)
![image](https://github.com/user-attachments/assets/8d9708ed-d916-41d3-8595-2131e7934297)
It's power mode in Korean

**Comment by creewick** [comment]
<img width="30%" align="right" alt="image" src="https://github.com/user-attachments/assets/40cc1d93-b350-488a-9b92-3d07e16702ed">

Hi! I will need more information about the issue.
Could you please check the following settings on your PC:

1. If it is a laptop, check that the **Battery Saver** option is **disabled** (example in the picture on the right)

2. Go to Settings — Personalization — Colors. <br> Check the **Transparency effects** toggle is **on**

3. Check if other apps have transparency effects

4. Tell me more about your Windows build. Is it an original build?  Do you use any tweakers or other software to disable system features?

<img width="30%" align="right" alt="image" src="https://github.com/user-attachments/assets/72cd0246-64f1-4a63-b0bc-6b05525380f9">

**Comment by sq4567** [comment]
It works after Transparency effects toggle on and restart the entire app.
Huge thx from Korea!!!!

**Comment by creewick** [comment]
Glad to hear it! Thanks for the feedback
