### ISSUE TITLE
Can you add the slider that controls opacity?

### ISSUE THREAD

**Issue by sq4567** [creewick/uWidgets#17]
I know that it's already a nice widget but if I can control the opacity and blur strength, it'll be much better!

**Comment by creewick** [comment]
Sure thing. But I need to clarify: you want to change background opacity, or make whole widget (with its content) semi-transparent?

As for the blur strength, it isn't really customisable with the Windows API. All I can do is to provide a blur type selector with the following options:
- Acrylic blur (currently used in the app)
- Mica blur (only works on Win11)
- Blur (very laggy and resource-draining)

I would like to avoid adding that selector, as I predict users to complain about these downsides.

**Comment by sq4567** [comment]
Only background, of course!

**Comment by creewick** [comment]
Added in 0.5.4 in Settings — Appearance

<img width="751" alt="image" src="https://github.com/user-attachments/assets/9b37518f-ed18-47ba-815a-7780ac2c09d4">
