### ISSUE TITLE
Lock size does not work?

### ISSUE THREAD

**Issue by Dadangdut33** [creewick/uWidgets#25]
**Describe the bug**
I enable the lock size in advanced setting but the widgets can still be resized.

**To Reproduce**
1. Go to advanced settings
2. Click on lock size
3. Resize widgets still works

**Expected behavior**
It should prevent resizing

**Screenshots**

**Desktop**
 - OS: Windows 11 23H2
 - Version: OS Build 22631.4037

**Additional context**
App version: 0.5.0-beta

**Comment by creewick** [comment]
Got it! The fix will be released later this week

**Comment by creewick** [comment]
Fixed in 0.5.1
