### ISSUE TITLE
Lowering Widget Size Broke Widgets Padding 

### ISSUE THREAD

**Issue by Dadangdut33** [creewick/uWidgets#28]
**Describe the bug**
Seems like after the new update lowering the widget size will make the widget impossible to use because they will go off screen.

**To Reproduce**
1. Go to widget size option
2. Click on widget size and lower it
3. See error

**Expected behavior**
Should scale the widget correctly

**Screenshots**

https://github.com/user-attachments/assets/6a4cea94-d56f-46ea-a168-47bfbaa01eb1

**Desktop**
 - OS: Windows 11 23H2
 - Version: OS Build 22631.4037

**Comment by creewick** [comment]
My bad, accidentally broke that feature 🙈

Fixed in 0.5.2
