### ISSUE TITLE
Weather forecast not working

### ISSUE THREAD

**Issue by EugeLynx** [creewick/uWidgets#3]
![изображение_2024-07-29_114622773](https://github.com/user-attachments/assets/aaff3d86-2b20-4c2f-b024-68d0c61af831)
Set for "Ekaterinburg Koltsovo Airport"

**Comment by creewick** [comment]
Hi! Does it work for other locations?
Can you please check the following URL, does it returns any errors for you?

https://api.open-meteo.com/v1/forecast?latitude=56.7431&longitude=60.8027&temperature_unit=celsius&current=temperature_2m,weathercode&hourly=temperature_2m,weathercode&daily=temperature_2m_min,temperature_2m_max,weathercode&timezone=auto

**Comment by EugeLynx** [comment]
Same for ohter locations
![image](https://github.com/user-attachments/assets/63458aba-9a40-41c5-96d3-04b34456b2fe)
![image](https://github.com/user-attachments/assets/67b44244-c469-4d57-8368-674e48b3f6d0)

And there's no error on the API from that URL
![image](https://github.com/user-attachments/assets/1fd10db7-96bc-441d-ae98-6f7b9c1f38d3)

**Comment by creewick** [comment]
There was a problem with building a request URL — CultureInfo on local machine is using `,` as decimal point, but API was expecting `.`

Fixed in [`8df407b`](https://github.com/creewick/uWidgets/commit/8df407b692f23d0083b05927e03138f23c2c1ea1)
