### ISSUE TITLE
Transparent Widgets

### ISSUE THREAD

**Issue by y0himba** [creewick/uWidgets#40]
**Is your feature request related to a problem? Please describe.** 
Not frustrating, simply a matter of preference

**Describe the solution you'd like**

I would like to be able to make the background entirely transparent.

![y0himba-FDocumentsRainmeterSkinsM-340](https://github.com/user-attachments/assets/b5753545-741d-46a8-b835-2246163129e4)

**Describe alternatives you've considered**
I tried to look in the code to see where I can edit, but I drive things for a living and couldn't figure it out.  

**Additional context**
![y0himba-FDocumentsRainmeterSkinsM-340](https://github.com/user-attachments/assets/b5753545-741d-46a8-b835-2246163129e4)

**Comment by creewick** [comment]
Hello! Background opacity level is already customizable. 
Change it to zero to make it completely transparent.

<img width="990" alt="Screenshot 2024-09-24 at 4 34 28 PM" src="https://github.com/user-attachments/assets/784d4c3b-2627-401e-8af1-b219bba8ba57">

If that's not what you're looking for, please provide more details and re-open the issue
