### ISSUE TITLE
Weather widget

### ISSUE THREAD

**Issue by AihamMostafaAwad** [creewick/uWidgets#6]
The weather widget is great until you choose medium or large sizes then it's just added space put the only info displayed is just the small size info in the same postion

**Desktop**
 - OS: [Windows 11 23H2]

**Comment by creewick** [comment]
That's true, I didn't have enough time to test the different sizes for a Forecast widget, so I included only small variant for that time.

However, it's ready now, you can check it out on [v.0.3.2](https://github.com/creewick/uWidgets/releases/tag/v0.3.2)

**Comment by AihamMostafaAwad** [comment]
I did notice once updated, it’s almost perfect

Sincerely,
         Aiham Awd
