### ISSUE TITLE
edit clock bug

### ISSUE THREAD

**Issue by wahyuabrory** [creewick/uWidgets#7]
![image](https://github.com/user-attachments/assets/8886b2df-f5f1-4bc2-ba1f-845ee6aca4fb)
when I tried to edit the time zone of my clock widget, I was surprised when I didn't see the time zone that I had previously set in the widget settings

**Comment by creewick** [comment]
Fixed in v0.4.0, please check

**Comment by wahyuabrory** [comment]
![Screenshot 12_08_2024 21_54_17](https://github.com/user-attachments/assets/75da8217-7ffa-4634-8867-9c800c61e962)

is this normal behavior? widget task into alt+tab cycle? and also in 0.3+ where I create a widget, it also created in another desktop when I create this widget, right now, it only create in current desktop.

**Comment by creewick** [comment]
No, this is not expected behaviour. Widget should not be displayed in Alt+Tab or Win+Tab.
I already found a fix for that, and will publish it today.

As for desktops: can you please provide more info? Do you mean virtual desktops (spaces) or different displays?

**Comment by creewick** [comment]
I guess you are talking about virtual desktops.
I see that widgets only appear on one desktop right now. 
But after fixing the bug with Alt+Tab, they appear on every desktops. I guess, these issues are related somehow.

<img width="459" alt="image" src="https://github.com/user-attachments/assets/79ac687c-ad23-409e-80a3-447cccfbd9fd">

I checked the same case with macOS native widgets. It seems, they appear on every virtual space. 
I will stick to that behaviour in my app as well.

**Comment by creewick** [comment]
Fixed in v0.4.1

**Comment by wahyuabrory** [comment]
nice, it works perfectly fine now
